### PR TITLE
[JENKINS-54096] Implemented GitLab permissions checking for multibranch, pipeline and downstream job types

### PR DESCRIPTION
**Pull request by betterphp**
This implements permissions checking for more job configurations. The logic for finding the repo name for a job has been separated from the actual permissions checking to make this easier.

The repo name is searched for as follows.

| Job Type | Repo URL Source | Notes |
| --- | --- | --- |
| Standard | Source Code Management | If a git SCM is used the remote URL is checked. This is the current behaviour. |
| Pipeline | Pipeline | If _Pipeline script from SCM_ is selected and it is a git repo that remote URL is checked. |
| Multibranch | Branch Sources | Each git SCM branch source remote URL is checked with the repo name from the first match being used for all branches in the view. |

Downstream projects refers to projects where a repo name was not found and there are upstream jobs configured. For these the parents are checked in the same way as described above and the permissions inherited. An upstream job is one that would trigger a build of the job, either via a build step or it's config.

### CODE REVIEW

**Comment by betterphp** [comment]
Looks like there are loads of errors relating to javadoc comments for files that I didn't edit, do they need to be fixed before this can be considered?

**Comment by JamesRItchie88** [comment]
+1

**Comment by Johnogram** [comment]
+1

**Comment by betterphp** [comment]
@elhabibmed closed with no comment?

**Comment by betterphp** [comment]
@elhabibmed

**Pull request closed without merging**
