### PR TITLE
Use group path from API

### PR DESCRIPTION
**Pull request by dee-see**
The group name here is generated by getting the URL of the group and then cutting it to its shortest but still unique expression. (Based on the comment saying this returns `The shorter, but still unique id of the group`, comments were removed for brevity).

```java
    @Override
    public String getName() {
        if (gitlabGroup != null) {
            return getAuthName();
        }
        return null;
    }

    private synchronized String getAuthName() {
        if (authName == null) {
            final String webUrl = gitlabGroup.getWebUrl();
            authName = shortenGroupUri(webUrl);
        }
        return authName;
    }

    static String shortenGroupUri(String webUrl) {
        return URI.create(webUrl).getPath().replace("/groups", "");
    }
```

With `https://gitlab.com/groups/my-org` the output is `/my-org`, however this code neglects the fact that a group name can start with "groups". With `https://gitlab.com/groups/groupsmy-org` the output is `my-org`. We're saved by the fact that the leading `/` is stripped and it's an invalid character in a group name, but it's not ideal. I'm not familiar with the lib that's used here to interact with the GitLab API but assuming the properties are mapped to what we can read in the [GitLab Groups API documentation](https://docs.gitlab.com/ee/api/groups.html) I believe all this code could be replaced by

```java
    @Override
    public String getName() {
        if (gitlabGroup != null) {
            return gitlabGroup.getPath();
        }
        return null;
    }
```

and that would take care of getting the unique path without the redundant `https://...` part.

### CODE REVIEW

**Comment by dee-see** [comment]
Hmm seems like something's wrong in the CI and I can't figure out what it is 🤔

**Comment by mohamedelhabib** [comment]
CI file because GitLabOAuthGroupDetails contains unused authName field
run mvn findbugs:check to see details (using java 8)

**Comment by dee-see** [comment]
Thanks!

**Comment by skorhone** [comment]
This change changes behavior on installations where gitlab is located in non-root path: e.g. https://mysite/gitlab .

**Comment by skorhone** [comment]
And it seems that support for nested groups is now completely broken. Granted authority no longer includes the full sub-group name

**Comment by skorhone** [comment]
I think instead of path you should have used fullPath. You need to be more careful with this kind of changes, after all this plugin is used for authentication/authorization

**Pull request merged**
